### ISSUE TITLE
Doesn't seem to work with 2.92

### ISSUE THREAD

**Issue by Gavinok** [doakey3/VSE_Transform_Tools#32]
When I try to use `g` in the preview I get the following error
```
Python: Traceback (most recent call last):
  File "/home/gavinok/.config/blender/2.92/scripts/addons/VSE_Transform_Tools/operators/grab/grab.py", line 328, in invoke
    if strip.use_translation:
AttributeError: 'MovieSequence' object has no attribute 'use_translation'

location: <unknown location>:-1
```
Here is my current blender version
```
Blender 2.92.0
        build date: 2021-02-25
        build time: 21:24:05
        build commit date: 2021-02-24
        build commit time: 16:25
        build hash: 02948a2cab44
        build platform: Linux
        build type: Release
        build c flags:  -Wall -Wcast-align -Werror=implicit-function-declaration -Werror=return-type -Werror=vla -Wstrict-prototypes -Wmissing-prototypes
-Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter
-Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wrestrict -Wnonnull -Wabsolute-value -Wuninitialized -Wredundant-decls -Wshadow -Wno-error=unused-but-set-variable -Wimplicit-fallthrough=5 -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fuse-ld=gold -fopenmp -std=gnu11 -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2
        build c++ flags:  -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Wno-char-subscripts -Wno-unknown-pragmas
-Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wformat-signedness -Wrestrict -Wuninitialized -Wundef -Wmissing-declarations -Wimplicit-fallthrough=5 -I /usr/include/python3.9 -fuse-ld=gold -fopenmp -std=c++17 -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2
        build link flags:  -Wl,--version-script='/build/blender/src/blender/source/creator/blender.map'
        build system: CMake
```
